'use strict';

const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');

function loadYamlBuilder() {
  const html = fs.readFileSync(require.resolve('../dash/dashboard/pages/intelligence.html'), 'utf8');
  const yamlStart = html.indexOf('const yamlQuote =');
  const yamlEnd = html.indexOf("\n      $('provisionForm')", yamlStart);
  assert.ok(yamlStart >= 0 && yamlEnd > yamlStart);
  const source = html.slice(yamlStart, yamlEnd);
  const context = {};
  vm.runInNewContext(`${source}; this.toPluginYaml = toPluginYaml;`, context);
  return context.toPluginYaml;
}

test('generated plugin config uses real YAML line breaks', () => {
  const toPluginYaml = loadYamlBuilder();
  const yaml = toPluginYaml({
    baseUrl: 'https://promcbot.dev',
    serverId: 'guild',
    instanceId: 'instance',
    networkId: '',
    minecraftServerId: '',
    serverName: 'test2',
    accessToken: 'access',
    signingSecret: 'secret',
    protocolVersion: '1',
  });
  assert.match(yaml, /# Generated by ProMcBot\. Store this file only on your Paper server\.\nbackend:\n/);
  assert.equal(yaml.includes('\\n'), false);
  assert.match(yaml, /\n  batch-size: 100\n  max-queue-size: 5000\n/);
});
