allowBuilds:
  '@root/acme': set this to true or false
  canvas: set this to true or false
  mongodb-memory-server: set this to true or false
  node: set this to true or false
  puppeteer: set this to true or false
  sharp: set this to true or false
