
chmod +x ./cloudflared
./cloudflared tunnel run --token eyJhIjoiY2Y1YTNjNDA3YTBlNWVkNjY2MzFjNWQ2ZWU4ZDdjMGMiLCJ0IjoiNmFlNjY3ZmEtZDRmMC00YjBmLTgyZDItYTc5MzgyMjE1MWEyIiwicyI6IllUSTFaVFV3T0dVdFpEVmpaaTAwTkRVMExXSmtOekV0WkdJellXWTFOekV6T0RrMCJ9| npm i canvas | node server.js